import type { PRRef } from "../types.js";
import { escapeHtml } from "./artifacts/html.js";

interface AssembleSection {
  title: string;
  html: string; // LLM-generated inner HTML fragment (may contain <style>/<script>)
}

export function assemble(input: {
  title: string;
  summary: string;
  ref: PRRef;
  sections: AssembleSection[];
}): string {
  const navItems = input.sections
    .map((s, i) => `<a href="#sec-${i}" class="heg-nav__item">${escapeHtml(s.title)}</a>`)
    .join("");

  const sectionHtml = input.sections
    .map(
      (s, i) =>
        `<section id="sec-${i}" class="heg-section">\n` +
        `<h2 class="heg-section__title">${escapeHtml(s.title)}</h2>\n` +
        s.html +
        `\n</section>`,
    )
    .join("\n\n");

  const refLabel = `${input.ref.owner}/${input.ref.repo}#${input.ref.number}`;

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>${escapeHtml(input.title)} — ${escapeHtml(refLabel)}</title>
<style>${BASE_STYLES}</style>
</head>
<body>
<header class="heg-header">
  <div class="heg-header__inner">
    <div class="heg-header__eyebrow">
      <a href="${escapeHtml(input.ref.url)}" target="_blank" rel="noopener">${escapeHtml(refLabel)}</a>
    </div>
    <h1 class="heg-header__title">${escapeHtml(input.title)}</h1>
    <p class="heg-header__summary">${escapeHtml(input.summary)}</p>
  </div>
</header>
<nav class="heg-nav"><div class="heg-nav__inner">${navItems}</div></nav>
<main class="heg-main">
${sectionHtml}
</main>
<footer class="heg-footer">Generated by <code>codexplaining</code></footer>
</body>
</html>
`;
}

const BASE_STYLES = `
:root {
  --heg-bg: #fafaf8;
  --heg-fg: #1c1c1e;
  --heg-fg-muted: #5b5b62;
  --heg-card: #fff;
  --heg-border: #e5e5e0;
  --heg-accent: #4338ca;
  --heg-accent-bg: #eef2ff;
  --heg-code-bg: #1f2937;
  --heg-code-fg: #e5e7eb;
  --heg-max: 880px;
}
@media (prefers-color-scheme: dark) {
  :root {
    --heg-bg: #0f1115;
    --heg-fg: #e8e8ea;
    --heg-fg-muted: #9b9ba6;
    --heg-card: #181a20;
    --heg-border: #2a2d36;
    --heg-accent: #818cf8;
    --heg-accent-bg: #1e1b3a;
    --heg-code-bg: #0b0d12;
    --heg-code-fg: #e5e7eb;
  }
}
* { box-sizing: border-box; }
html, body { margin: 0; padding: 0; }
body {
  background: var(--heg-bg);
  color: var(--heg-fg);
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  line-height: 1.55;
  font-size: 15px;
}
a { color: var(--heg-accent); text-decoration: none; }
a:hover { text-decoration: underline; }
.heg-header { border-bottom: 1px solid var(--heg-border); }
.heg-header__inner { max-width: var(--heg-max); margin: 0 auto; padding: 2rem 1.25rem 1.5rem; }
.heg-header__eyebrow { font-size: 0.8rem; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; color: var(--heg-fg-muted); }
.heg-header__title { margin: 0.25rem 0 0.4rem; font-size: 1.6rem; line-height: 1.25; }
.heg-header__summary { margin: 0; color: var(--heg-fg-muted); font-size: 0.95rem; max-width: 65ch; }
.heg-nav {
  position: sticky; top: 0; z-index: 10;
  background: color-mix(in srgb, var(--heg-bg) 92%, transparent);
  backdrop-filter: blur(8px);
  border-bottom: 1px solid var(--heg-border);
}
.heg-nav__inner {
  max-width: var(--heg-max); margin: 0 auto; padding: 0.5rem 1.25rem;
  display: flex; gap: 1rem; overflow-x: auto;
  font-size: 0.85rem;
}
.heg-nav__item { color: var(--heg-fg-muted); white-space: nowrap; }
.heg-nav__item:hover { color: var(--heg-fg); }
.heg-main { max-width: var(--heg-max); margin: 0 auto; padding: 1.5rem 1.25rem 3rem; display: flex; flex-direction: column; gap: 0; }
.heg-section { padding: 1.75rem 0; }
.heg-section + .heg-section { border-top: 1px solid var(--heg-border); }
.heg-section__title { margin: 0 0 1rem; font-size: 1.15rem; font-weight: 600; }
.heg-footer {
  max-width: var(--heg-max); margin: 0 auto;
  padding: 1.5rem 1.25rem 3rem; color: var(--heg-fg-muted); font-size: 0.8rem;
}
`;
